
server:
  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/felipemarinho/Dev/Alura/Spring Cloud/workspace/properties
 