
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loja
    username: postgres
    password: docker
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        type: trace
        use_sql_comments: true
